#main zagadnienia-magisterka/_quarto.yml
project:
  type: website
  output-dir: docs


website:
  title: "Coś tu będzie"
  description: "Notatki, przemyślenia i projekty"
  #favicon: favicon.png
  navbar:
    left:
      - text: "Home"
        href: index.qmd
    right:
      - icon: github
        href: https://github.com/Jascow01
      - icon: rss
        href: posts/index.xml
  page-footer:
    left: "© 2025 Szymon Door"
    right: "Zbudowano w [Quarto](https://quarto.org/)"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: left
    page-layout: article


